export const documentTypes = [
  { type: 'Business Permit', shortcut: 'BUSS-PER' },
  { type: 'Case', shortcut: 'CASE' },
  { type: 'Certification', shortcut: 'CERT' },
  { type: 'Contract of Service', shortcut: 'COS' },
  { type: 'Cheque', shortcut: 'CHQ' },
  { type: 'DTR', shortcut: 'DTR' },
  { type: 'Disbursement Voucher', shortcut: 'DV' },
  { type: 'Executive Order', shortcut: 'EO' },
  { type: 'IPCR/OPCR', shortcut: 'IPCR/OPCR' },
  { type: 'Letters', shortcut: 'LETTER' },
  { type: 'Leave', shortcut: 'LEAVE' },
  { type: 'Liquidation', shortcut: 'LIQUIDATION' },
  { type: 'Retirement', shortcut: 'RET' },
  { type: 'Memorandum Order', shortcut: 'MEMO' },
  { type: 'Notice', shortcut: 'NOTICE' },
  { type: 'Notice of Violation', shortcut: 'NOTI-VIOL' },
  { type: 'Office Order', shortcut: 'OFC-ORD' },
  { type: 'Other Documents', shortcut: 'OTR-DOC' },
  { type: 'Order of Payment', shortcut: 'ORD-PYMT' },
  { type: 'Ordinance', shortcut: 'ORD' },
  { type: 'OBR', shortcut: 'OBR' },
  { type: 'OBR/Payroll', shortcut: 'OBR/PYRL' },
  { type: 'Permit', shortcut: 'PERMIT' },
  { type: 'Project', shortcut: 'PROJ' },
  { type: 'PR/OBR', shortcut: 'PR/OBR' },
  { type: 'Purchase Request', shortcut: 'PR' },
  { type: 'Proposal', shortcut: 'PRPSL' },
  { type: 'Purchase Order', shortcut: 'PO' },
  { type: 'OBR/Reimbursement', shortcut: 'OBR/REIMB' },
  { type: 'Resolution', shortcut: 'RESO' },
  { type: 'Reports', shortcut: 'REPORT' },
  { type: 'Salary Loan', shortcut: 'SAL-LOAN' },
  { type: 'Show Cause', shortcut: 'SHW-CAUSE' },
  { type: 'Special Order', shortcut: 'SO' },
  { type: 'Travel Order', shortcut: 'TO' }
]

export const assigneeList = [
  'AS',
  'AR',
  'AB',
  'AL'
]

export const statusList = [
  { status: 'Received at MMO', color: '#ff5722' },
  { status: 'Received at MTO', color: '#000' },
  { status: 'Resolved', color: '#287f00' },
  { status: 'Pending for approval', color: '#997c00' },
  { status: 'Approved', color: '#287f00' },
  { status: 'Disapproved', color: '#e02626' },
  { status: 'For File', color: '#000' },
  { status: 'Confidential', color: '#000' },
  { status: 'For Further Instruction', color: '#997c00' },
  { status: 'Cancelled', color: '#e02626' },
  { status: 'Forwarded', color: '#2154db' },
  { status: 'Forwarded to MMO', color: '#a44508' },
  { status: 'Forwarded to MTO', color: '#1249ed' },
  { status: 'Others', color: '#000' }
]

export const superAdmins = [
  'berlcamp@gmail.com',
  'berlcampomanes@gmail.com'
]

export const barangays = [
  '50TH DISTRICT',
  'AGUADA',
  'BACOLOD',
  'BAGAKAY',
  'BALINTAWAK',
  'BANADERO',
  'BAYBAY SAN ROQUE',
  'BAYBAY SANTA CRUZ',
  'BAYBAY TRIUNFO',
  'BONGBONG',
  'CALABAYAN',
  'CAPUCAO C',
  'CAPUCAO P',
  'CARANGAN',
  'CARMEN ANNEX',
  'CATADMAN-MANABAY',
  'CAVINTE',
  'COGON',
  'DALAPANG',
  'DIGUAN',
  'DIMALUNA',
  'DONA CONSUELO',
  'EMBARGO',
  'GALA',
  'GANGO',
  'GOTOCAN DAKU',
  'GOTOCAN DIOT',
  'GUIMAD',
  'GUINGONA',
  'KINUMAN NORTE',
  'KINUMAN SUR',
  'LABINAY',
  'LABO',
  'LAM-AN',
  'LIPOSONG',
  'LITAPAN',
  'MALAUBANG',
  'MANAKA',
  'MANINGCOL',
  'MENTERING',
  'MOLICAY',
  'PANTAON',
  'PULOT',
  'SAN ANTONIO',
  'SANGAY DAKU',
  'SANGAY DIOT',
  'SINUSA',
  'STIMSON ABORDO',
  'TABID',
  'TINAGO',
  'TRIGOS'
]

export const reqList = [
  { label: 'Application Form', isComplete: false },
  { label: 'MOA', isComplete: false },
  { label: 'COR/COE', isComplete: false },
  { label: 'VALID ID', isComplete: false },
  { label: 'Cert. Residency', isComplete: false },
  { label: 'Cert. (indigency, pwd, sp)', isComplete: false },
  { label: 'LCR/PSA', isComplete: false },
  { label: 'Latest Report', isComplete: false },
  { label: 'Statement of Account', isComplete: false }
]
